# Generated by Django 6.0.6 on 2026-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_skills',
            field=models.TextField(blank=True),
        ),
    ]
