# Generated by Django 6.0.6 on 2026-06-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
