# Generated by Django 6.0.6 on 2026-06-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='job_title',
            field=models.CharField(default='Unknown Job', max_length=100),
            preserve_default=False,
        ),
    ]
