# Generated by Django 6.0.6 on 2026-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_interview_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_score',
            field=models.IntegerField(default=0),
        ),
    ]
