# Generated by Django 6.0.6 on 2026-06-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_resume_feedback_resume_resume_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='interview_questions',
            field=models.TextField(blank=True),
        ),
    ]
