# Generated by Django 6.0.6 on 2026-06-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_resume_interview_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skill_gap',
            field=models.TextField(blank=True),
        ),
    ]
